FROM node:20-slim

RUN apt-get update && \
    apt-get install -y procps && \
    apt-get install -y openssl

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate
RUN npm run start:dev